### ISSUE TITLE
hello, could you please offer me the dataset? thanks

### ISSUE THREAD

**Issue by yuanzilin** [atharsefid/Automatic-Slide-Generation#1]

**Comment by yuanzilin** [comment]
here is my email:1799926597@qq.com

**Comment by atharsefid** [comment]
The dataset is available [here](https://drive.google.com/file/d/1xYHXYoQBa7DJVrq0ePly58ioq2EmmVG8/view)
Please cite our paper if you use the data.

**Comment by yuanzilin** [comment]
> The dataset is available [here](https://drive.google.com/file/d/1xYHXYoQBa7DJVrq0ePly58ioq2EmmVG8/view)
> Please cite our paper if you use the data.

Absolutely! Thank you very much!

**Comment by yuanzilin** [comment]
> The dataset is available [here](https://drive.google.com/file/d/1xYHXYoQBa7DJVrq0ePly58ioq2EmmVG8/view)
> Please cite our paper if you use the data.

and if it is ok, could you please share the ILP code with me? I have try my best to find some code about ILP, but i haven't get any useful code
